export const studded_tot = {
  studded_nsv_y1_6: [
    {
      metric: "UCP",
      gis: 0.2,
      regular: 0.6,
      colorStones: 0.3,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 39.1,
    },
    {
      metric: "Share(%)",
      gis: 16.0,
      regular: 55.0,
      colorStones: 28.0,
      solitaireAUnder70C: 1.0,
      solitaireB70To100C: 0.0,
      solitaireC1CrtPlus: 0.0,
      solitaireD2CrtPlus: 0.0,
      total: 100.0,
    },
    {
      metric: "Tax",
      gis: 0.0,
      regular: 0.0,
      colorStones: 0.0,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 0.0,
    },
    {
      metric: "Discount",
      gis: 0.0,
      regular: 0.0,
      colorStones: 0.0,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 0.1,
    },
    {
      metric: "Discount(%)",
      gis: 7.9,
      regular: 8.5,
      colorStones: 2.8,
      solitaireAUnder70C: 10.5,
      solitaireB70To100C: 0.0,
      solitaireC1CrtPlus: 0.0,
      solitaireD2CrtPlus: 0.0,
      total: 0.2,
    },
    {
      metric: "NSV",
      gis: 0.1,
      regular: 0.5,
      colorStones: 0.3,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 39.0,
    },
    {
      metric: "NSVSummary",
      nsv: 39,
      gis: 0,
      regular: 0,
      colorStones: 0,
      solitaireAUnder70C: 0,
      solitaireB70To100C: 0,
      solitaireC1CrtPlus: 0,
      solitaireD2CrtPlus: 0,
    },
  ],
  columns: [
    "GIS",
    "Regular",
    "Color Stones",
    "Solitaire A(<70C)",
    "Solitaire B(70-100C)",
    "Solitaire C(1CRT+)",
    "Solitaire D(2CRT+)",
    "Total",
  ],
};
