export const studded_tot = {
  studded_nsv_y1_6: [
    {
      metric: "UCP",
      gis: 0.2,
      regular: 0.6,
      colorStones: 0.3,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 39.1,
    },
    {
      metric: "Share(%)",
      gis: 16.0,
      regular: 55.0,
      colorStones: 28.0,
      solitaireAUnder70C: 1.0,
      solitaireB70To100C: 0.0,
      solitaireC1CrtPlus: 0.0,
      solitaireD2CrtPlus: 0.0,
      total: 100.0,
    },
    {
      metric: "Tax",
      gis: 0.0,
      regular: 0.0,
      colorStones: 0.0,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 0.0,
    },
    {
      metric: "Discount",
      gis: 0.0,
      regular: 0.0,
      colorStones: 0.0,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 0.1,
    },
    {
      metric: "Discount(%)",
      gis: 7.9,
      regular: 8.5,
      colorStones: 2.8,
      solitaireAUnder70C: 10.5,
      solitaireB70To100C: 0.0,
      solitaireC1CrtPlus: 0.0,
      solitaireD2CrtPlus: 0.0,
      total: 0.2,
    },
    {
      metric: "NSV",
      gis: 0.1,
      regular: 0.5,
      colorStones: 0.3,
      solitaireAUnder70C: 0.0,
      solitaireB70To100C: null,
      solitaireC1CrtPlus: null,
      solitaireD2CrtPlus: null,
      total: 39.0,
    },
    {
      metric: "NSVSummary",
      nsv: 39,
      gis: 0,
      regular: 0,
      colorStones: 0,
      solitaireAUnder70C: 0,
      solitaireB70To100C: 0,
      solitaireC1CrtPlus: 0,
      solitaireD2CrtPlus: 0,
    },
  ],
  columns: [
    "GIS",
    "Regular",
    "Color Stones",
    "Solitaire A(<70C)",
    "Solitaire B(70-100C)",
    "Solitaire C(1CRT+)",
    "Solitaire D(2CRT+)",
    "Total",
  ],
  studded_bandwise_data: {
    data: [
      {
        lowerSlab: 0,
        upperSlab: 10,
        nsv: null,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
      },
      {
        lowerSlab: 10,
        upperSlab: 20,
        nsv: null,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
      },
      {
        lowerSlab: 20,
        upperSlab: 50,
        nsv: null,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
      },
      {
        lowerSlab: 50,
        upperSlab: 200000,
        nsv: null,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
      },
      {
        metric: "Overall NSV",
        nsv: null,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
      },
    ],
    columns: [
      "Lower slab",
      "Upper slab",
      "NSV",
      "GIS",
      "Regular",
      "Color Stones",
      "Solitaire A(<70C)",
      "Solitaire B(70-100C)",
      "Solitaire C(1CRT+)",
      "Solitaire D(2CRT+)",
    ],
  },

  studded_tot_refrence: {
    columns: [
      "Low",
      "High",
      "GIS",
      "Regular",
      "Color Stones",
      "Solitaire A(<70C)",
      "Solitaire B(70-100C)",
      "Solitaire C(1CRT+)",
      "Solitaire D(2CRT+)",
    ],
    data: [
      {
        low: 0,
        high: 10,
        gis: "10.0%",
        regular: "12.5%",
        colorStones: "5.0%",
        solitaireAUnder70C: "9.0%",
        solitaireB70To100C: "7.0%",
        solitaireC1CrtPlus: "5.0%",
        solitaireD2CrtPlus: "4.0%",
      },
      {
        low: 10,
        high: 20,
        gis: "9.0%",
        regular: "11.5%",
        colorStones: "4.5%",
        solitaireAUnder70C: "9.0%",
        solitaireB70To100C: "7.0%",
        solitaireC1CrtPlus: "5.0%",
        solitaireD2CrtPlus: "4.0%",
      },
      {
        low: 20,
        high: 50,
        gis: "7.0%",
        regular: "10.5%",
        colorStones: "4.0%",
        solitaireAUnder70C: "9.0%",
        solitaireB70To100C: "7.0%",
        solitaireC1CrtPlus: "5.0%",
        solitaireD2CrtPlus: "4.0%",
      },
      {
        low: 50,
        high: 200000,
        gis: "6.0%",
        regular: "9.5%",
        colorStones: "4.0%",
        solitaireAUnder70C: "9.0%",
        solitaireB70To100C: "7.0%",
        solitaireC1CrtPlus: "5.0%",
        solitaireD2CrtPlus: "4.0%",
      },
    ],
  },

  studdet_final_data: {
    columns: [
      "Low",
      "High",
      "GIS",
      "Regular",
      "Color Stones",
      "Solitaire A(<70C)",
      "Solitaire B(70-100C)",
      "Solitaire C(1CRT+)",
      "Solitaire D(2CRT+)",
      "Total",
    ],
    final_data: [
      {
        low: 0,
        high: 10,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
        total: null,
      },
      {
        low: 10,
        high: 20,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
        total: null,
      },
      {
        low: 20,
        high: 50,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
        total: null,
      },
      {
        low: 50,
        high: 200000,
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
        total: null,
      },
      {
        metric: "ToT",
        gis: null,
        regular: null,
        colorStones: null,
        solitaireAUnder70C: null,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
        total: null,
      },
      {
        metric: "UCP",
        gis: 0.2,
        regular: 0.6,
        colorStones: 0.3,
        solitaireAUnder70C: 0.0,
        solitaireB70To100C: null,
        solitaireC1CrtPlus: null,
        solitaireD2CrtPlus: null,
        total: 1.0,
      },
      {
        metric: "ToT %",
        gis: "0.0%",
        regular: "0.0%",
        colorStones: "0.0%",
        solitaireAUnder70C: "0.0%",
        solitaireB70To100C: "#DIV/0!",
        solitaireC1CrtPlus: "#DIV/0!",
        solitaireD2CrtPlus: "#DIV/0!",
        total: "0.0%",
      },
    ],
  },
};
