export const dummy_data = {
  ucp_sales_forcast: {
    row_data: [
      {
        category: "LCG",
        Y1: 2699,
        Y2: 3304,
        Y3: 3692,
        Y4: 4125,
        Y5: 4544,
        Y6: 4908,
      },
      {
        category: "MCG",
        Y1: 5606,
        Y2: 6861,
        Y3: 7668,
        Y4: 8567,
        Y5: 9438,
        Y6: 10193,
      },
      {
        category: "HCG",
        Y1: 2076,
        Y2: 2541,
        Y3: 2840,
        Y4: 3173,
        Y5: 3496,
        Y6: 3775,
      },
      {
        category: "Coins",
        Y1: 752,
        Y2: 921,
        Y3: 1044,
        Y4: 1184,
        Y5: 1304,
        Y6: 1409,
      },
    ],
    col: ["Y1", "Y2", "Y3", "Y4", "Y5", "Y6"],
  },
  financialSummary: {
    row_data: [
      {
        metric: "UCP",
        LCG: 26.99,
        MCG: 56.06,
        HCG: 20.76,
        Overall: 104,
      },
      {
        metric: "UCP Mix",
        LCG: "26%",
        MCG: "54%",
        HCG: "20%",
        Overall: "100%",
      },
      {
        metric: "AMC",
        LCG: 3,
        MCG: 9,
        HCG: 4,
        Overall: 16,
      },
      {
        metric: "AMC %",
        LCG: "12.6%",
        MCG: "20.0%",
        HCG: "28.0%",
        Overall: "19.7%",
      },
      {
        metric: "GST",
        LCG: 1,
        MCG: 2,
        HCG: 1,
        Overall: 3,
      },
      {
        metric: "Discount",
        LCG: 0.4,
        MCG: 1.21,
        HCG: 0.64,
        Overall: 2,
      },
      {
        metric: "Net AMC",
        LCG: 3,
        MCG: 8,
        HCG: 4,
        Overall: 14,
      },
      {
        metric: "GHS Discount",
        LCG: 0.11,
        MCG: 0.23,
        HCG: 0.08,
        Overall: 0.42,
      },
      {
        metric: "Stone",
        LCG: null,
        MCG: null,
        HCG: null,
        Overall: 0.83,
      },
      {
        metric: "NSV",
        LCG: 26,
        MCG: 53,
        HCG: 19,
        Overall: 98,
      },
    ],
    col: ["LCG", "MCG", "HCG", "Overall"],
  },

  net_amc_data: {
    nsvRangeSummary: [
      {
        Lower: 0,
        Upper: 20,
        NSV: 20.0,
        LCG: 0.5,
        MCG: 1.6,
        HCG: 0.8,
        HCG_Stone: 0.2,
      },
      {
        Lower: 20,
        Upper: 40,
        NSV: 20.0,
        LCG: 0.5,
        MCG: 1.6,
        HCG: 0.8,
        HCG_Stone: 0.2,
      },
      {
        Lower: 40,
        Upper: 60,
        NSV: 20.0,
        LCG: 0.5,
        MCG: 1.6,
        HCG: 0.8,
        HCG_Stone: 0.2,
      },
      {
        Lower: 60,
        Upper: 80,
        NSV: 20.0,
        LCG: 0.5,
        MCG: 1.6,
        HCG: 0.8,
        HCG_Stone: 0.2,
      },
      {
        Lower: 80,
        Upper: 100,
        NSV: 18.2,
        LCG: 0.5,
        MCG: 1.5,
        HCG: 0.7,
        HCG_Stone: 0.2,
      },
      {
        Lower: 100,
        Upper: 100000,
        NSV: null,
        LCG: null,
        MCG: null,
        HCG: null,
        HCG_Stone: null,
      },
      {
        Lower: "Total",
        Upper: "Total",
        NSV: 98.2,
        LCG: 2.5,
        MCG: 7.9,
        HCG: 3.8,
        HCG_Stone: 0.8,
      },
    ],
    columns: ["Lower", "Upper", "NSV", "LCG", "MCG", "HCG", "HCG_Stone"],
  },
  tot_percentage: {
    weightedRateSummary: [
      {
        Lower: 0,
        Upper: 20,
        LCG: "23.0%",
        MCG: "26.0%",
        HCG: "29.0%",
        HCG_Stone: "5.0%",
        Weighted_Rate: "25.9%",
      },
      {
        Lower: 20,
        Upper: 40,
        LCG: "20.0%",
        MCG: "23.0%",
        HCG: "27.0%",
        HCG_Stone: "5.0%",
        Weighted_Rate: "23.1%",
      },
      {
        Lower: 40,
        Upper: 60,
        LCG: "18.0%",
        MCG: "20.0%",
        HCG: "24.0%",
        HCG_Stone: "3.0%",
        Weighted_Rate: "20.3%",
      },
      {
        Lower: 60,
        Upper: 80,
        LCG: "16.0%",
        MCG: "18.0%",
        HCG: "21.0%",
        HCG_Stone: "3.0%",
        Weighted_Rate: "18.1%",
      },
      {
        Lower: 80,
        Upper: 100,
        LCG: "16.0%",
        MCG: "18.0%",
        HCG: "20.0%",
        HCG_Stone: "3.0%",
        Weighted_Rate: "17.9%",
      },
      {
        Lower: 100,
        Upper: 100000,
        LCG: "16.0%",
        MCG: "18.0%",
        HCG: "20.0%",
        HCG_Stone: "3.0%",
        Weighted_Rate: "17.9%",
      },
    ],
    columns: [
      "Lower",
      "Upper",
      "LCG",
      "MCG",
      "HCG",
      "HCG_Stone",
      "Weighted_Rate",
    ],
  },
};
