export const routes = {
  LOGIN: "/ThirdEye",
  NEW_STORE: "/ThirdEye/new/store",
  DARK_CATCHMENT: "/ThirdEye/dark/catchment/analysis",
  NEW_CITY_EXPANSION: "/ThirdEye/new/city/expansion",
  NEW_STR_PROJECTION: "/ThirdEye/new/store/projection",
  NEW_CITY_PROJECTION: "/ThirdEye/new/city/projection",
  HISTORY: "/ThirdEye/projection/history",
  STORE_CATCHMENT_ANALYSIS: "/ThirdEye/store/catchment/analysis",
  ADMIN_LOGIN: "/ThirdEye/admin_login",
  PLAIN_TOT_HOME: "/ThirdEye/plain_tot/home",
  STUDDED_TOT_HOME: "/ThirdEye/studded_tot/home",
  BPM_SUMMARY_HOME: "/ThirdEye/bpm_summary/home",
  ROI_HOME: "/ThirdEye/roi/home/page",
};
